XINU_PROJECT = xinu-stk500-main
MAIN_SRC = $(XINU_PROJECT).c

all: $(XINU_PROJECT)

#############################################################################
# Edit to change default Directory                                          #
#############################################################################
XINU_DIRECTORY = /Users/Xinu

AVR_XINUDIR = $(XINU_DIRECTORY)/avr-XinuExperimentalRoot
HOME = $(AVR_XINUDIR)
XINU = $(HOME)


TARGET=stk500


include $(XINU)/Makefile.include
