#
#  Make Xinu Manual Pages - only FILES change between man[01234]
#

DIR	=	../..
MACROS	=	$(DIR)/lib/tmac.an
NROFF = groff

.SUFFIXES:	.ms .ps .1 .2 .3 .4

.ms.ps:
		$(NROFF) -ms $< >$*.ps

.1.ps:
		$(NROFF) -mdoc $< >$*.ps

.2.ps:
#		cat pre_file >,$*
#		sed '0,/^\.Dt/d' $< >>,$* ; mv ,$* $*.2
		$(NROFF) -mdoc $< >$*.ps
		$(NROFF) -mdoc -Thtml $< >$*.2.html
		

.3.ps:
		$(NROFF) -mdoc $< >$*.ps

.4.ps:
		$(NROFF) -mdoc $< >$*.ps

FILES	= Intro2.ps	\
		access.ps	\
		chprio.ps	\
		close.ps	\
		control.ps	\
		create.ps	\
		freebuf.ps	\
		freemem.ps	\
		freestk.ps	\
		getaddr.ps	\
		getbuf.ps	\
		getc.ps	\
		getmem.ps	\
		getname.ps	\
		getnet.ps	\
		getpid.ps	\
		getprio.ps	\
		gettime.ps	\
		getutim.ps	\
		ip2name.ps	\
		kill.ps	\
		mark.ps	\
		mkpool.ps	\
		mount.ps	\
		nammap.ps	\
		namrepl.ps	\
		open.ps	\
		panic.ps	\
		pcount.ps	\
		pcreate.ps	\
		pdelete.ps	\
		pinit.ps	\
		preceive.ps	\
		preset.ps	\
		psend.ps	\
		putc.ps	\
		read.ps	\
		receive.ps	\
		recvclr.ps	\
		recvtim.ps	\
		remove.ps	\
		resume.ps	\
		scount.ps	\
		screate.ps	\
		sdelete.ps	\
		seek.ps	\
		send.ps	\
		sendf.ps	\
		setdev.ps	\
		setnok.ps	\
		signal.ps	\
		sleep.ps	\
		sreset.ps	\
		suspend.ps	\
		unmount.ps	\
		unsleep.ps	\
		wait.ps	\
		write.ps

all:		$(FILES)

install:
		@echo no installation possible - use "'make print'"

clean:
		rm -rf *.ps core ,* *.html

Intro1.ps:	Intro1.1
		$(NROFF) -mdoc Intro1.1 >Intro1.ps

Intro2.ps:	Intro2.2
		$(NROFF) -mdoc Intro2.2 >Intro2.ps

Intro3.ps:	Intro3.3
		$(NROFF) -mdoc Intro3.3 >Intro3.ps

Intro4.ps:	Intro4.4
		$(NROFF) -mdoc Intro4.4 >Intro4.ps
		
print:		listings

listings:	$(FILES)
#		cat *.ps | sed '1,2d;s/^/	/' | lpr
		echo $(MANPATH)
