.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.ds release-date February 8, 2011
.ds xinu-platform avr-Xinu
.\"
.Os XINU V7
.Dd \*[release-date] 
.Dt GETNAME \&2 \*[xinu-platform]
.Sh NAME
getname \- return the official Internet domain name of the local host
.Sh SYNOPSIS
.Em int *getname(name)
.br
.Em char *name;
.fi
.Sh DESCRIPTION
\f2Getname\f1 returns the least\-significant component of the
official Internet domain name of the local host using GETADDR(2) to
obtain the host's IP address, and IP2NAME(2) to translate the
IP address into a domain name.
For example, when executed on host \f2merlin.cs.purdue.edu\f1,
\f2getname\f1 returns the string \f2merlin\f1.
.Pp
Argument \f2name\f1 gives the starting address of an area in which the
name should be placed.
\f2Getname\f1 writes the name as a contiguous, null\-terminated
byte string.
.Sh SEE ALSO
ip2name(2), getaddr(2)
.Sh BUGS
There is no way to force \f2getname\f1 to return the full domain name.
