.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.ds release-date February 8, 2011
.ds xinu-platform avr-Xinu
.\"
.Os XINU V7
.Dd \*[release-date] 
.Dt READ \&2 \*[xinu-platform]
.Sh NAME
read \- device independent input routine
.Sh SYNOPSIS
.nf
.Em int read(dev, buffer, numchars)
.Em int dev;
.Em char *buffer;
.Em int numchars;
.fi
.Sh DESCRIPTION
.Ar Read
will read up to
.Ar numchars
bytes from the I/O device given by
.Ar dev.
It returns SYSERR if
.Ar dev
is incorrect.
It returns the number of characters read if successful.
The number of bytes actually returned depends on the device.
For example, when reading from a device of type "tty", each read
normally returns one line.
For a disk, however, each read returns one block and the argument
\f2numchars\f1 is taken to be the index of the disk block desired.
.Sh SEE ALSO
close(2), control(2), getc(2), open(2), putc(2), seek(2), write(2)
