# -*- makefile -*-
# dummy, default, makefile
#
#	We don't care what the Host OS thinks this file's attributes are
#	but we hope it's 'text'-like.
#
#	The other way is:
#
#	$ alias make=“make -f Makefile.make”
#
#	which is not very transparent.
#
include Makefile.make
